services:
  nginx:
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    depends_on:
      - php

  php:
    volumes:
      - ./www:/var/www/html
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql && php-fpm"

  mysql:
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    secrets:
      - mysql_root_password
      - mysql_user_password

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
    volumes:
      - ./entrypoint.sh:/custom-entrypoint.sh:ro
    entrypoint: ["/custom-entrypoint.sh"]
    command: ["apache2-foreground"]
    secrets:
      - mysql_root_password
    networks:
      - backend
      - frontend
    depends_on:
      - mysql

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt