services:
  nginx:
    image: nginx:1.25
    container_name: nginx_container
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    depends_on:
      - php
    networks:
      - frontend
      - backend

  php:
    image: php:8.2-fpm
    container_name: php_container
    volumes:
      - ./www:/var/www/html
    networks:
      - backend
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql && php-fpm"

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    secrets:
      - mysql_root_password
      - mysql_user_password
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
    volumes:
      - ./entrypoint.sh:/custom-entrypoint.sh:ro
    entrypoint: ["/custom-entrypoint.sh"]
    command: ["apache2-foreground"]
    secrets:
      - mysql_root_password
    networks:
      - backend
      - frontend
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  frontend:
  backend:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt